url: "https://mcvmcv.net" 
baseurl: "" 


collections: 
  books:
  articles:
  crumbs:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
    values:
      image_resize: "300x500"
